subset(denv_kenya, 
denv_kenya$negative_blank_visit_a_denv_stfd=="1" | denv_kenya$negative_repeat_visit_a_denv_stfd=="1" | denv_kenya$blank_positive_visit_a_denv_stfd=="1"| denv_kenya$blank_blank_visit_a_denv_stfd=="1"|denv_kenya$repeat_positive_visit_a_denv_stfd=="1"| denv_kenya$repeat_blank_visit_a_denv_stfd=="1" | denv_kenya$repeat_repeat_visit_a_denv_stfd=="1"
|denv_kenya$negative_blank_visit_b_denv_stfd=="1" | denv_kenya$negative_repeat_visit_b_denv_stfd=="1" | denv_kenya$blank_positive_visit_b_denv_stfd=="1"| denv_kenya$blank_blank_visit_b_denv_stfd=="1"|denv_kenya$repeat_positive_visit_b_denv_stfd=="1"| denv_kenya$repeat_blank_visit_b_denv_stfd=="1" | denv_kenya$repeat_repeat_visit_b_denv_stfd=="1"
|denv_kenya$negative_blank_visit_c_denv_stfd=="1" | denv_kenya$negative_repeat_visit_c_denv_stfd=="1" | denv_kenya$blank_positive_visit_c_denv_stfd=="1"| denv_kenya$blank_blank_visit_c_denv_stfd=="1"|denv_kenya$repeat_positive_visit_c_denv_stfd=="1"| denv_kenya$repeat_blank_visit_c_denv_stfd=="1" | denv_kenya$repeat_repeat_visit_c_denv_stfd=="1"
|denv_kenya$negative_blank_visit_d_denv_stfd=="1" | denv_kenya$negative_repeat_visit_d_denv_stfd=="1" | denv_kenya$blank_positive_visit_d_denv_stfd=="1"| denv_kenya$blank_blank_visit_d_denv_stfd=="1"|denv_kenya$repeat_positive_visit_d_denv_stfd=="1"| denv_kenya$repeat_blank_visit_d_denv_stfd=="1" | denv_kenya$repeat_repeat_visit_d_denv_stfd=="1"
|denv_kenya$negative_blank_visit_e_denv_stfd=="1" | denv_kenya$negative_repeat_visit_e_denv_stfd=="1" | denv_kenya$blank_positive_visit_e_denv_stfd=="1"| denv_kenya$blank_blank_visit_e_denv_stfd=="1"|denv_kenya$repeat_positive_visit_e_denv_stfd=="1"| denv_kenya$repeat_blank_visit_e_denv_stfd=="1" | denv_kenya$repeat_repeat_visit_e_denv_stfd=="1"
|denv_kenya$negative_blank_visit_f_denv_stfd=="1" | denv_kenya$negative_repeat_visit_f_denv_stfd=="1" | denv_kenya$blank_positive_visit_f_denv_stfd=="1"| denv_kenya$blank_blank_visit_f_denv_stfd=="1"|denv_kenya$repeat_positive_visit_f_denv_stfd=="1"| denv_kenya$repeat_blank_visit_f_denv_stfd=="1" | denv_kenya$repeat_repeat_visit_f_denv_stfd=="1"
|denv_kenya$negative_blank_visit_g_denv_stfd=="1" | denv_kenya$negative_repeat_visit_g_denv_stfd=="1" | denv_kenya$blank_positive_visit_g_denv_stfd=="1"| denv_kenya$blank_blank_visit_g_denv_stfd=="1"|denv_kenya$repeat_positive_visit_g_denv_stfd=="1"| denv_kenya$repeat_blank_visit_g_denv_stfd=="1" | denv_kenya$repeat_repeat_visit_g_denv_stfd=="1"
|denv_kenya$negative_blank_visit_h_denv_stfd=="1" | denv_kenya$negative_repeat_visit_h_denv_stfd=="1" | denv_kenya$blank_positive_visit_h_denv_stfd=="1"| denv_kenya$blank_blank_visit_h_denv_stfd=="1"|denv_kenya$repeat_positive_visit_h_denv_stfd=="1"| denv_kenya$repeat_blank_visit_h_denv_stfd=="1" | denv_kenya$repeat_repeat_visit_h_denv_stfd=="1"
)

subset(chikv_kenya, 
chikv_kenya$negative_blank_visit_a_chikv_stfd=="1" | chikv_kenya$negative_repeat_visit_a_chikv_stfd=="1" | chikv_kenya$blank_positive_visit_a_chikv_stfd=="1"| chikv_kenya$blank_blank_visit_a_chikv_stfd=="1"|chikv_kenya$repeat_positive_visit_a_chikv_stfd=="1"| chikv_kenya$repeat_blank_visit_a_chikv_stfd=="1" | chikv_kenya$repeat_repeat_visit_a_chikv_stfd=="1"
|chikv_kenya$negative_blank_visit_b_chikv_stfd=="1" | chikv_kenya$negative_repeat_visit_b_chikv_stfd=="1" | chikv_kenya$blank_positive_visit_b_chikv_stfd=="1"| chikv_kenya$blank_blank_visit_b_chikv_stfd=="1"|chikv_kenya$repeat_positive_visit_b_chikv_stfd=="1"| chikv_kenya$repeat_blank_visit_b_chikv_stfd=="1" | chikv_kenya$repeat_repeat_visit_b_chikv_stfd=="1"
|chikv_kenya$negative_blank_visit_c_chikv_stfd=="1" | chikv_kenya$negative_repeat_visit_c_chikv_stfd=="1" | chikv_kenya$blank_positive_visit_c_chikv_stfd=="1"| chikv_kenya$blank_blank_visit_c_chikv_stfd=="1"|chikv_kenya$repeat_positive_visit_c_chikv_stfd=="1"| chikv_kenya$repeat_blank_visit_c_chikv_stfd=="1" | chikv_kenya$repeat_repeat_visit_c_chikv_stfd=="1"
|chikv_kenya$negative_blank_visit_d_chikv_stfd=="1" | chikv_kenya$negative_repeat_visit_d_chikv_stfd=="1" | chikv_kenya$blank_positive_visit_d_chikv_stfd=="1"| chikv_kenya$blank_blank_visit_d_chikv_stfd=="1"|chikv_kenya$repeat_positive_visit_d_chikv_stfd=="1"| chikv_kenya$repeat_blank_visit_d_chikv_stfd=="1" | chikv_kenya$repeat_repeat_visit_d_chikv_stfd=="1"
|chikv_kenya$negative_blank_visit_e_chikv_stfd=="1" | chikv_kenya$negative_repeat_visit_e_chikv_stfd=="1" | chikv_kenya$blank_positive_visit_e_chikv_stfd=="1"| chikv_kenya$blank_blank_visit_e_chikv_stfd=="1"|chikv_kenya$repeat_positive_visit_e_chikv_stfd=="1"| chikv_kenya$repeat_blank_visit_e_chikv_stfd=="1" | chikv_kenya$repeat_repeat_visit_e_chikv_stfd=="1"
|chikv_kenya$negative_blank_visit_f_chikv_stfd=="1" | chikv_kenya$negative_repeat_visit_f_chikv_stfd=="1" | chikv_kenya$blank_positive_visit_f_chikv_stfd=="1"| chikv_kenya$blank_blank_visit_f_chikv_stfd=="1"|chikv_kenya$repeat_positive_visit_f_chikv_stfd=="1"| chikv_kenya$repeat_blank_visit_f_chikv_stfd=="1" | chikv_kenya$repeat_repeat_visit_f_chikv_stfd=="1"
|chikv_kenya$negative_blank_visit_g_chikv_stfd=="1" | chikv_kenya$negative_repeat_visit_g_chikv_stfd=="1" | chikv_kenya$blank_positive_visit_g_chikv_stfd=="1"| chikv_kenya$blank_blank_visit_g_chikv_stfd=="1"|chikv_kenya$repeat_positive_visit_g_chikv_stfd=="1"| chikv_kenya$repeat_blank_visit_g_chikv_stfd=="1" | chikv_kenya$repeat_repeat_visit_g_chikv_stfd=="1"
|chikv_kenya$negative_blank_visit_h_chikv_stfd=="1" | chikv_kenya$negative_repeat_visit_h_chikv_stfd=="1" | chikv_kenya$blank_positive_visit_h_chikv_stfd=="1"| chikv_kenya$blank_blank_visit_h_chikv_stfd=="1"|chikv_kenya$repeat_positive_visit_h_chikv_stfd=="1"| chikv_kenya$repeat_blank_visit_h_chikv_stfd=="1" | chikv_kenya$repeat_repeat_visit_h_chikv_stfd=="1"
)